workflows:
  android-build:
    name: NexBeat Build

    environment:
      flutter: stable

    scripts:
      - ./gradlew clean
      - ./gradlew assembleRelease

    artifacts:
      - app/build/outputs/**/*.apk
